# <span style="color:red"> The Lab Partner Problem </span>

<font size="5">

You need to choose a lab partner, and you want the one with the best lab skills (a higher number is better). The rules:

- You interview the candidates one at a time, **in a random order**.
- Right after each interview you must decide **on the spot**: pick this person, or let them go.
- If you let someone go, you **cannot go back** to them later.
- You know nothing about the candidates you haven't interviewed yet.
- You must end up with *somebody* - so if you reach the last person without having chosen anyone, you are stuck with that last person.

This famous puzzle is also known as the *secretary problem*, the *fussy suitor problem*, and the *best choice problem*. The best strategies all have the same shape:

> Interview the first **N** people **without choosing anyone**, and remember the highest lab skills you saw among them - call it the **benchmark**. Then keep interviewing, and choose the **first person whose lab skills beat the benchmark**.

There is a formula for the best choice of N, but we will find it **by simulation**, building up the answer one piece at a time.

In [2]:
lab_partners = {
    "Abed":      {"month": "March",     "day": 23, "year": 2007, "lab_skills": 3.24},
    "Britta":    {"month": "July",      "day": 14, "year": 1998, "lab_skills": 1.51},
    "Jeff":      {"month": "December",  "day": 8,  "year": 1990, "lab_skills": 0.51},
    "Shirley":   {"month": "January",   "day": 19, "year": 1990, "lab_skills": 6.72},
    "Annie":     {"month": "September", "day": 27, "year": 2007, "lab_skills": 6.72},
    "Troy":      {"month": "June",      "day": 5,  "year": 2007, "lab_skills": 3.66},
    "Pierce":    {"month": "December",  "day": 30, "year": 1962, "lab_skills": 0.58},
    "Chang":     {"month": "April",     "day": 17, "year": 1987, "lab_skills": 5.07},
    "Craig":     {"month": "August",    "day": 11, "year": 1985, "lab_skills": 0.37},
    "Magnitude": {"month": "February",  "day": 22, "year": 1983, "lab_skills": 4.34},
    "Garrett":   {"month": "October",   "day": 3,  "year": 2001, "lab_skills": 0.70},
    "Vicki":     {"month": "May",       "day": 29, "year": 2003, "lab_skills": 0.91},
    "Todd":      {"month": "March",     "day": 16, "year": 1997, "lab_skills": 9.99},
    "Starburns": {"month": "July",      "day": 7,  "year": 1982, "lab_skills": 8.27},
    "Neil":      {"month": "January",   "day": 25, "year": 1998, "lab_skills": 1.24},
    "Leonard":   {"month": "November",  "day": 13, "year": 1993, "lab_skills": 2.23},
    "Willy":     {"month": "September", "day": 4,  "year": 1981, "lab_skills": 6.27},
    "Pavel":     {"month": "June",      "day": 21, "year": 1980, "lab_skills": 9.48},
    "Quendra":   {"month": "December",  "day": 9,  "year": 1982, "lab_skills": 5.77},
    "Rich":      {"month": "April",     "day": 28, "year": 1986, "lab_skills": 3.97},
    "Duncan":    {"month": "August",    "day": 15, "year": 1987, "lab_skills": 9.76},
    "Hickey":    {"month": "February",  "day": 6,  "year": 1996, "lab_skills": 0.47},
    "Buzz":      {"month": "October",   "day": 24, "year": 1999, "lab_skills": 8.58},
    "Rachel":    {"month": "May",       "day": 18, "year": 1980, "lab_skills": 2.90},
    "Ian":       {"month": "March",     "day": 12, "year": 1997, "lab_skills": 1.44},
    "Elroy":     {"month": "July",      "day": 30, "year": 1986, "lab_skills": 1.18},
    "Frankie":   {"month": "November",  "day": 2,  "year": 2002, "lab_skills": 3.08},
    "Natalie":   {"month": "September", "day": 20, "year": 2000, "lab_skills": 8.16},
    "Owen":      {"month": "June",      "day": 11, "year": 2002, "lab_skills": 1.81},
    "Paula":     {"month": "December",  "day": 26, "year": 1997, "lab_skills": 5.82},
    "Quinn":     {"month": "April",     "day": 1,  "year": 1993, "lab_skills": 6.39},
    "Roger":     {"month": "August",    "day": 17, "year": 1987, "lab_skills": 3.72},
    "Sara":      {"month": "February",  "day": 8,  "year": 1994, "lab_skills": 5.48},
    "Tim":       {"month": "October",   "day": 22, "year": 1998, "lab_skills": 0.63},
    "Uma":       {"month": "May",       "day": 14, "year": 1988, "lab_skills": 0.60},
    "Victor":    {"month": "January",   "day": 29, "year": 2005, "lab_skills": 2.06},
    "Wendy":     {"month": "July",      "day": 5,  "year": 2007, "lab_skills": 6.80},
    "Xavier":    {"month": "March",     "day": 19, "year": 1980, "lab_skills": 4.28},
    "Yolanda":   {"month": "November",  "day": 10, "year": 2004, "lab_skills": 3.14},
    "Zara":      {"month": "September", "day": 3,  "year": 2005, "lab_skills": 5.86},
    "Alex":      {"month": "June",      "day": 27, "year": 1985, "lab_skills": 4.53},
    "Blake":     {"month": "December",  "day": 16, "year": 2002, "lab_skills": 3.00},
    "Casey":     {"month": "April",     "day": 7,  "year": 1993, "lab_skills": 7.94},
    "Dana":      {"month": "August",    "day": 23, "year": 1990, "lab_skills": 6.99},
    "Eli":       {"month": "February",  "day": 18, "year": 1988, "lab_skills": 2.44},
    "Fiona":     {"month": "October",   "day": 12, "year": 1984, "lab_skills": 5.74},
    "George":    {"month": "May",       "day": 25, "year": 1986, "lab_skills": 5.25},
    "Hana":      {"month": "January",   "day": 6,  "year": 2004, "lab_skills": 8.75},
    "Ivan":      {"month": "July",      "day": 21, "year": 1990, "lab_skills": 7.29},
    "Julia":     {"month": "March",     "day": 15, "year": 1983, "lab_skills": 2.88},
}

print(len(lab_partners), "potential lab partners")

50 potential lab partners


<font size = "5">

**1.** Warm-up: looking things up in a dictionary of dictionaries.

- Print Duncan's lab skills.
- Store Starburns' month and day in two variables and print a sentence describing his birthday using an f-string.
- Using `if` / `elif` / `else`, compare Shirley's and Annie's lab skills and print who would make the better lab partner. (Careful: how many possible outcomes are there?)

In [ ]:
print(lab_partners["Duncan"]["lab_skills"])
Starburns_month = lab_partners["Starburns"]["month"]
Starburns_day = lab_partners["Starburns"]["day"]
print(f"Starburns birthday is {Starburns_month} {Starburns_day}.")
if lab_partners["Shirley"]["lab_skills"] > lab_partners["Annie"]["lab_skills"]:
    print("Shirley is a better lab partner.")
elif lab_partners["Annie"]["lab_skills"] > lab_partners["Shirley"]["lab_skills"]:
    print("Annie is a better lab partner.")
else:
    print("They are equally good.")

9.76
Starburns birthyday is July 7.
They are equally good.


<font size = "5">

**2.** A random interview order.

- Using `list( )` and `.keys( )`, make a list called `interview_order` containing all the candidates' names.
- Shuffle it with `random.shuffle`.
- Print `len(interview_order)` to check that all 50 candidates are there.
- Using a `for` loop over `range(10)`, print the first ten interviews in the form:

  `Interview 0: Abed has lab skills 3.24`

  (You will need the two-step lookup to get each person's lab skills.)
- Run the cell several times - the order should change every time.

In [33]:
import random

interview_order = list(lab_partners.keys())

random.shuffle(interview_order)

print(len(interview_order))

for i in range(10):
    print("Interview " + str(i) + ": " +  interview_order[i] + " has lab skills " + str(lab_partners[interview_order[i]]["lab_skills"]))



50
Interview 0: Troy has lab skills 3.66
Interview 1: Annie has lab skills 6.72
Interview 2: Abed has lab skills 3.24
Interview 3: Quinn has lab skills 6.39
Interview 4: Quendra has lab skills 5.77
Interview 5: Paula has lab skills 5.82
Interview 6: Todd has lab skills 9.99
Interview 7: Ivan has lab skills 7.29
Interview 8: Fiona has lab skills 5.74
Interview 9: Zara has lab skills 5.86


<font size = "5">

**3.** Finding the highest lab skills  of the firs N students interviewed. Set `N = 10`.

- Using a `for` loop over `range(N)` and a **running maximum** (starting from `best_of_first_N = 0` and at each step in the loop update `best_of_first_N` if the current lab skills are higher than the current value of `best_of_first_N`), find the highest lab skills among the first `N` people in `interview_order`.
- Print the final vlue of `best_of_first_N`, we'll call this the benchmark lab skills.
- Every candidate in our class has lab skills above 0. Why does starting the running maximum at 0 depend on that?

In [ ]:
N = 10

best_of_first_N = 0.0


for i in range(N):
    if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
        best_of_first_N = lab_partners[interview_order[i]]["lab_skills"]

print("The best lab skill is " + str(best_of_first_N))

#otherwise the comparison may not be working, because negative numbers would not be considered in the comparison.
#If there are negative numbers, maximum could be incorrectly left at 2 even if 2 is not the correct max.



The best lab skill is 9.99


<font size = "5">

**4.** The selection phase. Now continue interviewing from position `N` onwards.

- *Before* the loop, set `chosen_name = interview_order[-1]`. If nobody ever beats the benchmark, you are stuck with the last person. (Why do we set this *before* the loop?)
- Loop over `range(N, len(interview_order))`. Stop at the *first* person whose lab skills beat `best_of_first_N`: store their name in `chosen_name` and `break`.
- Print who you chose and their lab skills.

The strongest candidate in the whole class is Todd, with lab skills 9.99. Did the strategy find Todd? Re-run Exercises 2-4 a few times and see how often it does.

In [ ]:
chosen_name = interview_order[-1]#this way we have a benchmark to compare to
# default: stuck with the last person.
# We set it BEFORE the loop so it only survives
# if the loop never finds anyone better.



for i in range(N,len(interview_order)):
    if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
        chosen_name= interview_order[i]
        break

print(chosen_name + ": " + str(lab_partners[chosen_name]["lab_skills"]))

#No, don't always find todd.

Chang: 5.07


<font size = "5">

**5.** The selection rule of the lab partner problem asks one small question over and over: *does this person's skill beat the benchmark?* Let's turn that question into a function.

- Write a function `beats_benchmark` with two parameters, `skill` and `benchmark`.
- Inside the function, write an `if`/`else` statement: if `skill > benchmark`, return `True`; otherwise return `False`.
- Using a `for` loop over the list below, apply your function to every score with `benchmark = 6.0`. At the end of the loop you should have a list of 10 elements, each either `True` or `False`.
- Bonus: `True` counts as 1 and `False` counts as 0, so `np.sum` of your list counts how many candidates beat the benchmark. Try it.

In [60]:
import numpy as np

skill_scores = [3.24, 1.51, 0.51, 6.72, 6.72, 3.66, 0.58, 5.07, 0.37, 4.34]

# your code here

def beats_benchmark(skill, benchmark):
    if skill > benchmark:
        return True
    else:
        return False

beats = []

for score in skill_scores:
    beats.append(beats_benchmark(score, 6.0))

print(beats)
print("Counts: " + str(np.sum(beats)))


[False, False, False, True, True, False, False, False, False, False]
Counts: 2


<font size = "5">

**6.** In Lecture 9 we printed lines like `Interview 0: Abed has lab skills 3.24`. Write a function that builds that sentence for us:

- The function should have three parameters: `position`, `name`, and `skill`.
- The return value should be the **string** `"Interview {position}: {name} has lab skills {skill}"` (use an f-string).
- Call your function at least twice with different arguments and print the results - once using keywords (`position = ...`), and once without.

In [62]:
# your code here

def build(position, name, skill):
    return(f"Interview {position}: {name} has lab skills {skill }")

print(build(position = 1, name = "Bob", skill = 3.6))
print(build(2, "Emily", 6.3))




Interview 1: Bob has lab skills 3.6
Interview 2: Emily has lab skills 6.3


<font size = "5">

**7.** Putting Exercises 2-4 together, one **trial** is: *shuffle the interview order, find the benchmark from the first N people, then select the first person who beats it.* Combine them into a single cell that produces one number, `chosen_skill`, for one random ordering (keep `N = 10` for now).

Each run of the cell is one possible version of your semester. Run it a few times.

In [ ]:
interview_order = list(lab_partners.keys())

random.shuffle(interview_order)


best_of_first_N = 0.0

N = 10 

for i in range(N):
    if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
        best_of_first_N = lab_partners[interview_order[i]]["lab_skills"]


chosen_name = interview_order[-1]#this way we have a benchmark to compare to
# default: stuck with the last person.
# We set it BEFORE the loop so it only survives
# if the loop never finds anyone better.



for i in range(N,len(interview_order)):
    if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
        chosen_name= interview_order[i]
        break

print(chosen_name + ": " + str(lab_partners[chosen_name]["lab_skills"]))

50
Duncan: 9.76


<font size = "5">

**8.** Package the complete trial above into a function:

- Define a function `run_one_trial` with a single parameter, `N`.
- The body is the cell above: shuffle, benchmark phase, selection phase. (The function will *read* the global dictionary `lab_partners` - just like `lab_skills_of` did in Section III.)
- The function should have **two return values**: `chosen_name` and `chosen_skill`.
- Test it by calling it a few times with `N = 10` and printing who you got.

Which variables in your function are **local**? After restarting and running only your function cell, check that `interview_order` does not appear in your workspace until *you* create it.

In [127]:
def run_one_trial(N):
    # your code here (adapt the cell above)
    interview_order = list(lab_partners.keys())
    random.shuffle(interview_order)

    best_of_first_N = 0.0

    for i in range(N):
        if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
            best_of_first_N = lab_partners[interview_order[i]]["lab_skills"]


    chosen_name = interview_order[-1]

    for i in range(N,len(interview_order)):
        if lab_partners[interview_order[i]]["lab_skills"] > best_of_first_N:
            chosen_name= interview_order[i]
            break

    chosen_skill = lab_partners[chosen_name]["lab_skills"]


    return chosen_name, chosen_skill


# test it a few times:
chosen_name, chosen_skill = run_one_trial(10)
print(f"You chose {chosen_name}, whose lab skills are {chosen_skill}.")

#best_of_first_N, interview_order are all local varaibles

You chose Hana, whose lab skills are 8.75.


<font size = "5">

**9.** One trial is just luck; the *average over many trials* measures the strategy. Using your new function:

- Run 100 trials with `N = 10` inside a `for` loop, appending each trial's `chosen_skill` to a list `chosen_skills`.
- Print the average with `np.mean`.

Compare the size of this cell to what it would have looked like last class, before we had a function! Then edit the cell and try `N = 0` and `N = 40` - do the averages behave the way you expect from Lecture 9?

In [ ]:
chosen_skills = []

for i in range(100):
    chosen_name, chosen_skill = run_one_trial(10)
    chosen_skills.append(chosen_skill)

print(chosen_skills)
print(np.mean(chosen_skills))

#Yes they do behave the way I expect, the best averages are produced by N=10 still. 

[8.75, 6.72, 8.75, 9.99, 9.99, 9.99, 9.99, 9.99, 9.76, 9.76, 9.76, 8.58, 9.99, 9.99, 9.48, 9.76, 9.99, 9.76, 9.76, 9.99, 9.76, 9.48, 9.48, 9.99, 9.48, 9.48, 4.28, 7.94, 9.99, 9.99, 9.48, 9.48, 9.48, 8.16, 6.72, 9.76, 9.48, 9.76, 7.29, 8.75, 9.48, 8.75, 9.99, 9.99, 9.99, 5.74, 0.51, 2.88, 3.72, 9.99, 5.82, 9.99, 9.99, 8.58, 8.27, 3.72, 8.58, 9.99, 9.99, 9.76, 9.99, 8.16, 9.99, 1.44, 9.99, 8.75, 8.75, 8.58, 6.72, 9.76, 6.8, 8.75, 9.48, 8.58, 9.48, 5.48, 9.76, 9.99, 9.76, 8.27, 8.75, 9.76, 1.51, 9.99, 9.99, 6.72, 8.75, 9.48, 9.99, 1.24, 9.99, 0.37, 9.99, 9.76, 2.9, 2.44, 9.76, 0.37, 3.72, 9.99]
8.2866


<font size = "5">

**10.** Now, the numerical answer. Which N gives the best average lab partner?

- Loop over every `N` in `range(num_candidates)`.
- For each N, compute the 100-trial average from Exercise 7.
- Track the winner with a **running maximum**: keep variables `best_average` and `best_N`, and update *both* whenever an average beats the current best.
- At the end, print the best N and its average.

Run the whole cell several times. Does the *same* N win every time? Next class we will draw a picture that explains what is going on.

In [ ]:
num_candidates = len(lab_partners)
num_trials = 100

best_average = 0
best_N = 0

for N in range(num_candidates):
    chosen_skills = []
    for i in range(num_trials):
        chosen_name, chosen_skill = run_one_trial(N)
        chosen_skills.append(chosen_skill)
    
    average = np.mean(chosen_skills)
    if average > best_average:
        best_average = average
        best_N = N

print(f"Best N is {best_N}, best average is {best_average}")

#No, not the same N win every time




print(f"The best N was {best_N}, with an average partner skill of {best_average}")

Best N is 11, best average is 8.6564
The best N was 11, with an average partner skill of 8.6564
